### ISSUE TITLE
multi monitor toast position

### ISSUE THREAD

**Issue by ItamarShDev** [Rmano/gse-switch-focus-mode#1]
the toast has a weird position when using the extension in full width

**Comment by Rmano** [comment]
Can you explain better? The "toast" (I imagine it is the notification message) should appear at the center of the main monitor, and it happens in my two multi-monitor configuration.

What do you mean with "in full width"? If your are using xinerama or something that makes the two monitors looks as a single one to the X server, strange things could happen.

Can you add a screenshot?

**Comment by ItamarShDev** [comment]
See in the attached picture.
I use 24'' screen as main and the 13'' laptop's screen as the second
the popup is positioned in a weird location.

![screenshot from 2017-06-13 11-43-15](https://user-images.githubusercontent.com/953371/27073734-920a145c-502d-11e7-9e4a-d37f93cb2037.png)

**Comment by Rmano** [comment]
Is the main monitor an HDPI device? This is strange --- I can't reproduce it myself. 
The lines that set the pop-up position are these: 
```
let monitor = Main.layoutManager.primaryMonitor;
text.set_position(Math.floor(monitor.width / 2 - text.width / 2),
    Math.floor(monitor.height / 2 - text.height / 2));
```
...which I copied from other extensions (I never managed to find a document with the description of the API). 

So what I am suspecting is that if the first screen is HDPI, there is some scaling that is not uniformly applied to both the "layout manager" and to the "text position". 

I am quite at a loss here ---  is there another extension you have that shows this kind of pop-ups in the correct position?

**Comment by Rmano** [comment]
By the way, this is how it looks here:

![workspace 1_057](https://user-images.githubusercontent.com/6414907/27085386-6235e72a-504f-11e7-9191-360f637fa201.png)

**Comment by ItamarShDev** [comment]
My setup is:
A 13.3'' laptop as secondary screen
A 23'' screen (1920*1080) as primary display

the toast is sown in my laptop (even though its the secondary one) and not centered

**Comment by Rmano** [comment]
Yep, I saw it. But I can't find anything in documentation (really, I can't find the documentation at all) and I can't reproduce it, so I am stalled.

**Comment by ItamarShDev** [comment]
Will check myself too, if ill have some free time
If i'll found the reason, a PR will be sent.
Thanks
