### ISSUE TITLE
Add a Shortcut

### ISSUE THREAD

**Issue by lwbaqueros** [Rmano/gse-switch-focus-mode#3]
Would be nice if there is a way to add a Shortcut for changing between the modes?

**Comment by Rmano** [comment]
I'd love it... but I struggle to find any documentation for writing these extensions. If you can point to something... ;-)

**Comment by xoxoMarzy** [comment]
I very much like this Playlist on YT: https://youtube.com/playlist?list=PLr3kuDAFECjZhW-p56BoVB7SubdUHBVQT
I'm a beginner to coding and I find it somewhat easy to follow
