### ISSUE TITLE
Extension is not compatible with the newest gnome-shell 45

### ISSUE THREAD

**Issue by ayangd** [Rmano/gse-switch-focus-mode#7]
GNOME Shell Extension page of this extension shows incompatible when trying to install the extension.

**Comment by Rmano** [comment]
Ah, I've yet to try it with 45... I have 44.5 installed. As soon as Arch updates it, I'll try to check and upload.

In the meantime, you can try to install it manually and just change the version in `metadata.json` like this:

```
 "shell-version": [
    "3.38",
    "40",
    "41",
    "42",
    "43",
    "44",
    "45"
  ],
```

(notice the added `45` line) and see if it works (I hope so because I have a bit of difficulty staying up-to-date with gnome...)

If you can confirm that it works, I can make an update even if blind on my side...

**Comment by ayangd** [comment]
Sadly, it doesn't work like that.

This probably helps: https://gjs.guide/extensions/upgrading/gnome-shell-45.html  
It now uses ESM for loading extensions.

Also, I'm on Arch and you can probably upgrade your gnome too.

**Comment by Rmano** [comment]
Ah, ok. 

Well, I'll tackle this as soon as I can, but that probably means once the term is over --- I have a lot of day job pressure now, and this seems not trivial. Thanks for the link, it seems very useful.

**Comment by Rmano** [comment]
I created a `legacy2` branch and bumped the version, although clearly, the extension is not working for Gnome 45. I am still quite busy, but I think that as soon as Manjaro updates my Gnome-Shell, I'll try to fix it.

**Comment by Rmano** [comment]
Note to self: see https://github.com/timbertson/gnome-shell-scroll-workspaces/pull/57

**Comment by Rmano** [comment]
I tried a go at it today, but I really can't understand how to change the code; it will need a lot more study for this. It *should* be easy (it's just switching a setting), but I can't see how to do it. So I re-state the "help needed" thing.

**Comment by Rmano** [comment]
The version in #8 do work, in a fashion. I can't get to use the right icons, and the OSD messages are not shown, but it switches the focus mode (I think).

**Comment by Rmano** [comment]
I uploaded a version that works on gnome-shell 45 today. I do not know if it will be accepted, though, because the code is somewhat messy.

You can always download the extension from here.

**Comment by Rmano** [comment]
The version for gnome-shell 45 has been accepted on the gnome.extensions.org site, it's on line now.
Closing this issue and thanks for the heads-on!
